<x-layouts.app>
    <x-slot:title>Linguistic Data Integrity & References — Quranic Arabic</x-slot:title>

    <div class="space-y-12 max-w-5xl mx-auto pb-8">
        <!-- Hero Section -->
        <div class="space-y-4">
            <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#1B4D3E]/10 dark:bg-emerald-950/50 border border-[#1B4D3E]/20 dark:border-emerald-500/30 text-xs font-semibold text-[#1B4D3E] dark:text-emerald-400">
                <span class="w-2 h-2 rounded-full bg-[#1B4D3E] dark:bg-emerald-400 animate-pulse"></span>
                <span>Scholarly Authenticity & Attribution</span>
            </div>
            
            <h1 class="text-3xl sm:text-4xl lg:text-5xl font-display font-semibold tracking-tight text-[#181C1E] dark:text-white leading-[1.15]">
                Linguistic Sources & Verification Integrity
            </h1>
            
            <p class="text-base sm:text-lg text-[#5C656C] dark:text-[#94A3B8] max-w-3xl leading-relaxed">
                Quranic Arabic adheres strictly to canonical Mushaf editions, internationally peer-reviewed linguistic corpora, and classical lexicons. Zero Quranic text, word roots, or grammatical rules are hallucinated or generated by AI models.
            </p>
        </div>

        <!-- Verification Protocol (3 Pillars) -->
        <div class="space-y-4">
            <div class="flex items-center justify-between">
                <h2 class="text-xs font-bold uppercase tracking-wider text-[#9A722C] dark:text-amber-400">
                    The 3-Pillar Verification Protocol
                </h2>
                <span class="text-xs text-[#5C656C] dark:text-[#94A3B8]">Single Source of Truth</span>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-5">
                <!-- Pillar 1 -->
                <div class="rounded-2xl bg-white dark:bg-[#131926] border border-[#E8E2D8] dark:border-[#1E2738] p-6 space-y-3 shadow-xs hover:border-[#1B4D3E]/40 dark:hover:border-emerald-500/40 transition-colors">
                    <div class="flex items-center justify-between">
                        <div class="w-10 h-10 rounded-2xl bg-[#1B4D3E]/10 dark:bg-emerald-950/50 text-[#1B4D3E] dark:text-emerald-400 flex items-center justify-center font-bold text-sm">
                            01
                        </div>
                        <span class="px-2.5 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wider bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
                            Canonical
                        </span>
                    </div>
                    <h3 class="text-base font-semibold text-[#181C1E] dark:text-white">Uthmanic Medina Mushaf</h3>
                    <p class="text-xs text-[#5C656C] dark:text-[#94A3B8] leading-relaxed">
                        Every letter, diacritical vowel (tashkīl), and verse boundary matches the Medina Mushaf standard verified by the <strong>Tanzil Project</strong> and King Fahd Glorious Quran Printing Complex (KFGQPC).
                    </p>
                </div>

                <!-- Pillar 2 -->
                <div class="rounded-2xl bg-white dark:bg-[#131926] border border-[#E8E2D8] dark:border-[#1E2738] p-6 space-y-3 shadow-xs hover:border-[#1B4D3E]/40 dark:hover:border-emerald-500/40 transition-colors">
                    <div class="flex items-center justify-between">
                        <div class="w-10 h-10 rounded-2xl bg-[#9A722C]/10 dark:bg-amber-950/50 text-[#9A722C] dark:text-amber-400 flex items-center justify-center font-bold text-sm">
                            02
                        </div>
                        <span class="px-2.5 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wider bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300">
                            Peer-Reviewed
                        </span>
                    </div>
                    <h3 class="text-base font-semibold text-[#181C1E] dark:text-white">Morphological Treebank</h3>
                    <p class="text-xs text-[#5C656C] dark:text-[#94A3B8] leading-relaxed">
                        Grammatical case endings, parts of speech, and verbal derivation forms are cross-referenced directly with the <strong>University of Leeds Quranic Arabic Corpus</strong> ontology.
                    </p>
                </div>

                <!-- Pillar 3 -->
                <div class="rounded-2xl bg-white dark:bg-[#131926] border border-[#E8E2D8] dark:border-[#1E2738] p-6 space-y-3 shadow-xs hover:border-[#1B4D3E]/40 dark:hover:border-emerald-500/40 transition-colors">
                    <div class="flex items-center justify-between">
                        <div class="w-10 h-10 rounded-2xl bg-[#1B4D3E]/10 dark:bg-emerald-950/50 text-[#1B4D3E] dark:text-emerald-400 flex items-center justify-center font-bold text-sm">
                            03
                        </div>
                        <span class="px-2.5 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wider bg-sky-100 text-sky-800 dark:bg-sky-950 dark:text-sky-300">
                            Classical Sanad
                        </span>
                    </div>
                    <h3 class="text-base font-semibold text-[#181C1E] dark:text-white">Authoritative Lexicography</h3>
                    <p class="text-xs text-[#5C656C] dark:text-[#94A3B8] leading-relaxed">
                        Tri-literal roots, semantic nuances, and makhārij articulation points are verified against <strong>Lane’s Lexicon</strong>, <strong>Al-Mufradāt</strong> (Al-Isfahani), and <strong>Al-Jazariyyah</strong>.
                    </p>
                </div>
            </div>
        </div>

        <!-- Primary Authoritative Sources Grid -->
        <div class="space-y-6">
            <div class="space-y-1">
                <h2 class="text-xl sm:text-2xl font-semibold text-[#181C1E] dark:text-white tracking-tight">
                    Canonical Sources & Datasets
                </h2>
                <p class="text-xs sm:text-sm text-[#5C656C] dark:text-[#94A3B8]">
                    Details of the academic databases, linguistic corpora, and digital archives ingested.
                </p>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <!-- Source 1: Tanzil -->
                <div class="rounded-2xl bg-white dark:bg-[#131926] border border-[#E8E2D8] dark:border-[#1E2738] p-6 sm:p-7 space-y-5 flex flex-col justify-between shadow-xs">
                    <div class="space-y-3">
                        <div class="flex items-center justify-between gap-2">
                            <span class="px-2.5 py-1 rounded-lg text-[11px] font-semibold tracking-wide bg-[#1B4D3E]/10 dark:bg-emerald-950/50 text-[#1B4D3E] dark:text-emerald-400">
                                UTHMANIC TEXT & TASHKĪL
                            </span>
                            <span class="text-[11px] font-mono text-[#5C656C] dark:text-[#94A3B8]">Since 2007</span>
                        </div>
                        <h3 class="text-lg font-semibold text-[#181C1E] dark:text-white flex items-center gap-2">
                            <span>Tanzil Project</span>
                            <span class="text-xs font-normal text-[#5C656C] dark:text-[#94A3B8]">(tanzil.net)</span>
                        </h3>
                        <p class="text-xs sm:text-sm text-[#5C656C] dark:text-[#94A3B8] leading-relaxed">
                            Tanzil provides the gold-standard Unicode-compliant Uthmanic Quran text audited against the Medina Mushaf (KFGQPC edition). It supplies our definitive text baseline, vowelling marks, pause notations, and surah/ayah numbering.
                        </p>
                        <div class="flex flex-wrap gap-1.5 pt-2">
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Medina Mushaf Standard</span>
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Audited Tashkeel</span>
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Unicode Pauses</span>
                        </div>
                    </div>
                    <div class="pt-4 border-t border-[#E8E2D8]/60 dark:border-[#1E2738]">
                        <a href="https://tanzil.net" target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-1.5 text-xs font-semibold text-[#1B4D3E] dark:text-emerald-400 hover:underline">
                            <span>Visit Tanzil Project</span>
                            <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                            </svg>
                        </a>
                    </div>
                </div>

                <!-- Source 2: Leeds Quranic Arabic Corpus -->
                <div class="rounded-2xl bg-white dark:bg-[#131926] border border-[#E8E2D8] dark:border-[#1E2738] p-6 sm:p-7 space-y-5 flex flex-col justify-between shadow-xs">
                    <div class="space-y-3">
                        <div class="flex items-center justify-between gap-2">
                            <span class="px-2.5 py-1 rounded-lg text-[11px] font-semibold tracking-wide bg-[#9A722C]/10 dark:bg-amber-950/50 text-[#9A722C] dark:text-amber-400">
                                MORPHOLOGY & SYNTACTIC TREEBANK
                            </span>
                            <span class="text-[11px] font-mono text-[#5C656C] dark:text-[#94A3B8]">Univ. of Leeds</span>
                        </div>
                        <h3 class="text-lg font-semibold text-[#181C1E] dark:text-white flex items-center gap-2">
                            <span>Quranic Arabic Corpus</span>
                            <span class="text-xs font-normal text-[#5C656C] dark:text-[#94A3B8]">(corpus.quran.com)</span>
                        </h3>
                        <p class="text-xs sm:text-sm text-[#5C656C] dark:text-[#94A3B8] leading-relaxed">
                            Created by the Language Research Group at the University of Leeds (directed by Kais Dukes). Provides word-by-word morphological analysis, syntactic trees, part-of-speech tags, and root linkages for all 77,430 words of the Quran.
                        </p>
                        <div class="flex flex-wrap gap-1.5 pt-2">
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">77,430 Tagged Words</span>
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Tri-Literal Roots</span>
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Grammatical Cases</span>
                        </div>
                    </div>
                    <div class="pt-4 border-t border-[#E8E2D8]/60 dark:border-[#1E2738]">
                        <a href="https://corpus.quran.com" target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-1.5 text-xs font-semibold text-[#1B4D3E] dark:text-emerald-400 hover:underline">
                            <span>Explore Corpus Ontology</span>
                            <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                            </svg>
                        </a>
                    </div>
                </div>

                <!-- Source 3: Quran.com & EveryAyah -->
                <div class="rounded-2xl bg-white dark:bg-[#131926] border border-[#E8E2D8] dark:border-[#1E2738] p-6 sm:p-7 space-y-5 flex flex-col justify-between shadow-xs">
                    <div class="space-y-3">
                        <div class="flex items-center justify-between gap-2">
                            <span class="px-2.5 py-1 rounded-lg text-[11px] font-semibold tracking-wide bg-sky-100 text-sky-800 dark:bg-sky-950 dark:text-sky-300">
                                WORD AUDIO & RECITATION CDN
                            </span>
                            <span class="text-[11px] font-mono text-[#5C656C] dark:text-[#94A3B8]">Quran.com API v4</span>
                        </div>
                        <h3 class="text-lg font-semibold text-[#181C1E] dark:text-white flex items-center gap-2">
                            <span>EveryAyah & Quran.com</span>
                            <span class="text-xs font-normal text-[#5C656C] dark:text-[#94A3B8]">(api.quran.com)</span>
                        </h3>
                        <p class="text-xs sm:text-sm text-[#5C656C] dark:text-[#94A3B8] leading-relaxed">
                            Word-by-word authentic audio pronunciations and full-ayah recitations by Sheikh Mishary Rashid Alafasy, streamed seamlessly via the open-access EveryAyah audio archive and Quran.com CDN endpoints.
                        </p>
                        <div class="flex flex-wrap gap-1.5 pt-2">
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Word Pronunciation</span>
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Murattal Recitation</span>
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Zero Latency CDN</span>
                        </div>
                    </div>
                    <div class="pt-4 border-t border-[#E8E2D8]/60 dark:border-[#1E2738]">
                        <a href="https://quran.com" target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-1.5 text-xs font-semibold text-[#1B4D3E] dark:text-emerald-400 hover:underline">
                            <span>View Quran.com API Documentation</span>
                            <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                            </svg>
                        </a>
                    </div>
                </div>

                <!-- Source 4: Classical Arabic Lexicons -->
                <div class="rounded-2xl bg-white dark:bg-[#131926] border border-[#E8E2D8] dark:border-[#1E2738] p-6 sm:p-7 space-y-5 flex flex-col justify-between shadow-xs">
                    <div class="space-y-3">
                        <div class="flex items-center justify-between gap-2">
                            <span class="px-2.5 py-1 rounded-lg text-[11px] font-semibold tracking-wide bg-purple-100 text-purple-800 dark:bg-purple-950 dark:text-purple-300">
                                CLASSICAL LEXICOGRAPHY
                            </span>
                            <span class="text-[11px] font-mono text-[#5C656C] dark:text-[#94A3B8]">Taj al-Arus & Lisan</span>
                        </div>
                        <h3 class="text-lg font-semibold text-[#181C1E] dark:text-white">
                            Classical Dictionaries & Concordances
                        </h3>
                        <p class="text-xs sm:text-sm text-[#5C656C] dark:text-[#94A3B8] leading-relaxed">
                            Tri-literal root definitions and semantic nuances rely on the classical monumental works:
                        </p>
                        <div class="space-y-1.5 text-xs text-[#5C656C] dark:text-[#94A3B8]">
                            <div class="flex items-start gap-2">
                                <span class="text-[#9A722C] font-bold">•</span>
                                <span><strong>Lane’s Arabic-English Lexicon:</strong> Edward William Lane’s 8-volume masterpiece based on Tāj al-ʿArūs.</span>
                            </div>
                            <div class="flex items-start gap-2">
                                <span class="text-[#9A722C] font-bold">•</span>
                                <span><strong>Al-Mufradāt fī Gharīb al-Qurʾān:</strong> Al-Rāghib al-Iṣfahānī’s classical seminal Quranic semantic dictionary.</span>
                            </div>
                            <div class="flex items-start gap-2">
                                <span class="text-[#9A722C] font-bold">•</span>
                                <span><strong>Hans Wehr:</strong> Dictionary of Modern Written Arabic (ed. J. Milton Cowan).</span>
                            </div>
                        </div>
                    </div>
                    <div class="pt-4 border-t border-[#E8E2D8]/60 dark:border-[#1E2738] text-xs text-[#5C656C] dark:text-[#94A3B8]">
                        Standard Academic Citations
                    </div>
                </div>

                <!-- Source 5: Tajweed & Phonetics -->
                <div class="rounded-2xl bg-white dark:bg-[#131926] border border-[#E8E2D8] dark:border-[#1E2738] p-6 sm:p-7 space-y-5 flex flex-col justify-between shadow-xs">
                    <div class="space-y-3">
                        <div class="flex items-center justify-between gap-2">
                            <span class="px-2.5 py-1 rounded-lg text-[11px] font-semibold tracking-wide bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
                                TAJWEED SCIENCE & PHONETICS
                            </span>
                            <span class="text-[11px] font-mono text-[#5C656C] dark:text-[#94A3B8]">Imam Ibn al-Jazari</span>
                        </div>
                        <h3 class="text-lg font-semibold text-[#181C1E] dark:text-white">
                            Al-Muqaddimah al-Jazariyyah
                        </h3>
                        <p class="text-xs sm:text-sm text-[#5C656C] dark:text-[#94A3B8] leading-relaxed">
                            Letter articulation points (<em>makhārij</em>) and phonetic acoustic characteristics (<em>ṣifāt lāzimah wa ʿāriḍah</em>) are codified directly from the didactic poem of Imam Shams al-Dīn Ibn al-Jazarī (751–833 AH), the master authority of Quranic recitation sciences.
                        </p>
                        <div class="flex flex-wrap gap-1.5 pt-2">
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">17 Makharij Points</span>
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Hams, Jahr, Qalqalah</span>
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Tafkhīm & Tarqīq</span>
                        </div>
                    </div>
                    <div class="pt-4 border-t border-[#E8E2D8]/60 dark:border-[#1E2738] text-xs text-[#5C656C] dark:text-[#94A3B8]">
                        Authentic Recitation Sanad
                    </div>
                </div>

                <!-- Source 6: Translations -->
                <div class="rounded-2xl bg-white dark:bg-[#131926] border border-[#E8E2D8] dark:border-[#1E2738] p-6 sm:p-7 space-y-5 flex flex-col justify-between shadow-xs">
                    <div class="space-y-3">
                        <div class="flex items-center justify-between gap-2">
                            <span class="px-2.5 py-1 rounded-lg text-[11px] font-semibold tracking-wide bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300">
                                MEANINGS & TRANSLATIONS
                            </span>
                            <span class="text-[11px] font-mono text-[#5C656C] dark:text-[#94A3B8]">English & Bengali</span>
                        </div>
                        <h3 class="text-lg font-semibold text-[#181C1E] dark:text-white">
                            Vetted Quranic Translations
                        </h3>
                        <p class="text-xs sm:text-sm text-[#5C656C] dark:text-[#94A3B8] leading-relaxed">
                            English renderings are taken from <strong>Saheeh International</strong>, celebrated for linguistic faithfulness to classical exegesis. Bengali meanings are cross-checked with the authentic translations of <strong>Dr. Mujibur Rahman</strong> and <strong>Mawlana Muhiuddin Khan</strong>.
                        </p>
                        <div class="flex flex-wrap gap-1.5 pt-2">
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Saheeh International (EN)</span>
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Dr. Mujibur Rahman (BN)</span>
                            <span class="px-2 py-0.5 rounded-md bg-[#FAF8F5] dark:bg-[#182030] text-[11px] text-[#5C656C] dark:text-[#94A3B8] border border-[#E8E2D8] dark:border-[#222E42]">Word-for-Word Alignment</span>
                        </div>
                    </div>
                    <div class="pt-4 border-t border-[#E8E2D8]/60 dark:border-[#1E2738] text-xs text-[#5C656C] dark:text-[#94A3B8]">
                        Strictly Faithful Translation Pairings
                    </div>
                </div>
            </div>
        </div>

        <!-- Verification Matrix Table -->
        <div class="space-y-4">
            <h2 class="text-xl font-semibold text-[#181C1E] dark:text-white tracking-tight">
                Data Verification Matrix
            </h2>

            <div class="rounded-2xl bg-white dark:bg-[#131926] border border-[#E8E2D8] dark:border-[#1E2738] shadow-xs">
                <div class="overflow-x-auto">
                    <table class="w-full text-left text-[11px] sm:text-xs min-w-[560px]">
                        <thead class="bg-[#FAF8F5] dark:bg-[#151C2C] border-b border-[#E8E2D8] dark:border-[#1E2738] text-[#5C656C] dark:text-[#94A3B8] uppercase tracking-wider font-semibold">
                            <tr>
                                <th class="py-3 px-3 sm:py-3.5 sm:px-5">Data Domain</th>
                                <th class="py-3 px-3 sm:py-3.5 sm:px-5">Primary Source</th>
                                <th class="py-3 px-3 sm:py-3.5 sm:px-5">Verification Benchmark</th>
                                <th class="py-3 px-3 sm:py-3.5 sm:px-5 text-right">Audit Status</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-[#E8E2D8] dark:divide-[#1E2738] text-[#181C1E] dark:text-gray-200">
                            <tr>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 font-semibold">Alphabet & Makharij</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 text-[#5C656C] dark:text-[#94A3B8]">Al-Jazariyyah + Arabic Phonetics</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5">17 distinct articulation organs</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 text-right whitespace-nowrap">
                                    <span class="inline-flex items-center gap-1 sm:gap-1.5 px-1.5 sm:px-2 py-0.5 rounded-full text-[9px] sm:text-[10px] font-semibold bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
                                        <span>✓</span> 100%
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 font-semibold">Quranic Text</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 text-[#5C656C] dark:text-[#94A3B8]">Tanzil Project (tanzil.net)</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5">KFGQPC Medina Mushaf 1405 AH</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 text-right whitespace-nowrap">
                                    <span class="inline-flex items-center gap-1 sm:gap-1.5 px-1.5 sm:px-2 py-0.5 rounded-full text-[9px] sm:text-[10px] font-semibold bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
                                        <span>✓</span> 100%
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 font-semibold">Morphology & Treebank</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 text-[#5C656C] dark:text-[#94A3B8]">Leeds Quranic Arabic Corpus</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5">Syntactic tagging & word segments</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 text-right whitespace-nowrap">
                                    <span class="inline-flex items-center gap-1 sm:gap-1.5 px-1.5 sm:px-2 py-0.5 rounded-full text-[9px] sm:text-[10px] font-semibold bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
                                        <span>✓</span> 100%
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 font-semibold">Top 100 Vocabulary</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 text-[#5C656C] dark:text-[#94A3B8]">Corpus Quran Frequency Database</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5">Occurrences covering ~50% Quran tokens</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 text-right whitespace-nowrap">
                                    <span class="inline-flex items-center gap-1 sm:gap-1.5 px-1.5 sm:px-2 py-0.5 rounded-full text-[9px] sm:text-[10px] font-semibold bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
                                        <span>✓</span> 100%
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 font-semibold">Audio Pronunciation</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 text-[#5C656C] dark:text-[#94A3B8]">Quran.com Audio CDN (EveryAyah)</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5">Sheikh Mishary Rashid Alafasy</td>
                                <td class="py-2.5 px-3 sm:py-3.5 sm:px-5 text-right whitespace-nowrap">
                                    <span class="inline-flex items-center gap-1 sm:gap-1.5 px-1.5 sm:px-2 py-0.5 rounded-full text-[9px] sm:text-[10px] font-semibold bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
                                        <span>✓</span> Active
                                    </span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <!-- Open Audit & Feedback -->
        <div class="rounded-2xl bg-gradient-to-br from-white to-[#FAF8F5] dark:from-[#111723] dark:to-[#0C111C] border border-[#E8E2D8] dark:border-[#1E2738] p-5 sm:p-8 space-y-4 shadow-xs">
            <div class="flex items-center gap-3">
                <div class="w-9 h-9 rounded-xl bg-[#1B4D3E] text-white flex items-center justify-center font-bold text-sm">
                    ق
                </div>
                <div>
                    <h3 class="text-base font-semibold text-[#181C1E] dark:text-white">Community & Scholarly Audit</h3>
                    <p class="text-xs text-[#5C656C] dark:text-[#94A3B8]">Transparent, open-source verification</p>
                </div>
            </div>
            
            <p class="text-xs sm:text-sm text-[#5C656C] dark:text-[#94A3B8] leading-relaxed">
                We invite students of knowledge, scholars, and computational linguists to audit our database. If you observe any typographical nuance, missing shaddah, or transliteration improvement, please submit an issue on our GitHub repository. Every report is cross-verified directly against the Tanzil Medina standard and Leeds treebank.
            </p>

            <div class="pt-2 flex flex-col sm:flex-row sm:items-center gap-3 sm:gap-4">
                <a href="https://github.com/fazleyrabby/learn-arabic/issues" target="_blank" rel="noopener noreferrer" class="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-[#1B4D3E] hover:bg-[#153D31] text-white text-xs font-semibold shadow-xs transition-colors text-center">
                    <span>Submit Correction on GitHub</span>
                    <svg class="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                    </svg>
                </a>
                
                <a href="{{ route('dashboard') }}" class="inline-flex items-center justify-center sm:justify-start gap-1.5 text-xs font-semibold text-[#5C656C] dark:text-[#94A3B8] hover:text-[#181C1E] dark:hover:text-white transition-colors">
                    <span>Back to Learning Path</span>
                    <span>&rarr;</span>
                </a>
            </div>
        </div>
    </div>
</x-layouts.app>
